Updating vm instance to allow for RDMA nic-types (private preview only
GoogleCloudPlatform/cluster-toolkit pull request #2878
Opened 2024-08-06 18:36 UTC by cdunbar13

Adding RDMA to list of possible nic-types.  This isn't currently available unless a user has a private provider with the feature built in, as it is private preview.

2024-08-06 22:13 UTC, tpdownes requested changes

2024-08-09 18:13 UTC, cdunbar13 commented on modules/compute/vm-instance/variables.tf
> +variable "pre_existing_placement_policy" {
Removed.

2024-08-12 21:29 UTC, tpdownes approved these changes
Please create a task for future work to adopt [optional object type attributes](https://developer.hashicorp.com/terraform/language/expressions/type-constraints#optional-object-type-attributes) in the vm-instance module. This code requires a bit of YAML sophistication to adopt in a blueprint.

2024-08-12 21:32 UTC, tpdownes requested changes
I think you need a corresponding change in the variable description for modules/compute/vm-instance/variables.tf

2024-08-23 12:27 UTC, closed without merging