Update batch image to hpc-rocky-linux-8
GoogleCloudPlatform/cluster-toolkit pull request #2884
Opened 2024-08-07 18:58 UTC by ankitkinra

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cluster Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2024-08-07 20:00 UTC, rohitramu approved these changes

2024-08-12 23:21 UTC, nick-stroud requested changes

2024-08-12 23:21 UTC, nick-stroud commented on examples/serverless-batch.yaml
As discussed in chat, I think we should be updating the default here: https://github.com/GoogleCloudPlatform/cluster-toolkit/blob/954105b37e4f6c1046ddc8cb1b9731c8c05f1d1e/modules/scheduler/batch-job-template/variables.tf#L200-L201

(and running both integration tests)

2024-08-13 17:08 UTC, nick-stroud approved these changes

2024-08-13 18:08 UTC, rohitramu approved these changes

2024-08-13 20:40 UTC, merged