Annuay/add machine type availability checks
GoogleCloudPlatform/cluster-toolkit pull request #3003
Opened 2024-09-04 19:01 UTC by annuay-google

### Submission Checklist

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cluster Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2024-09-04 19:09 UTC, annuay-google commented
./run --pr 3003 --tags slurm6

2024-09-04 19:20 UTC, annuay-google commented
./gcbrun --pr 3003 --tags slurm6

2024-09-04 20:08 UTC, mr0re1 approved these changes
Please run all tests

2024-09-05 14:32 UTC, tpdownes commented
@annuay-google please rebase this PR off the current state of the develop branch.

2024-09-05 14:34 UTC, tpdownes requested changes
Please rebase off current state of develop and run the Slurm 6 integration tests.

2024-09-06 20:24 UTC, annuay-google commented
> Please rebase off current state of develop and run the Slurm 6 integration tests.

Rebased and ran all Slurm 6 tests. All were successful

2024-09-09 20:40 UTC, tpdownes requested changes

2024-09-11 19:20 UTC, tpdownes approved these changes
We'll review how to avoid gaps between blueprint under examples directory and the overrides in our integration tests and create a task for future work.

2024-09-11 19:36 UTC, merged