Add dynamic setup of gpu_limit in gke-job-template module
GoogleCloudPlatform/cluster-toolkit pull request #3319
Opened 2024-11-28 14:51 UTC by mohitchaurasia91

### Submission Checklist

NOTE: Community submissions can take up to 2 weeks to be reviewed.

Please take the following actions before submitting this pull request.

* Fork your PR branch from the Toolkit "develop" branch (not main)
* Test all changes with pre-commit in a local branch [#](https://goo.gle/hpc-toolkit#development)
* Confirm that "make tests" passes all tests
* Add or modify unit tests to cover code changes
* Ensure that unit test coverage remains above 80%
* Update all applicable documentation
* Follow Cluster Toolkit Contribution guidelines [#](https://goo.gle/hpc-toolkit-contributing)

2024-11-29 15:42 UTC, annuay-google commented on modules/compute/gke-job-template/main.tf
> +  )
Appreciate the effort to explain this out with a detailed comment. Can we instead break this expression into meaningful named smaller conditionals, and then hierarchically combine them?

2024-11-29 15:45 UTC, annuay-google commented on modules/compute/gke-job-template/main.tf
> +  )
Rationale: let the code explain itself, this will need us to keep the code and comment in sync

2024-11-29 15:46 UTC, annuay-google requested changes
Please add a section/comment on verifying the change- is there a way to see how many GPUs nvidia-smi has requested for e.g.?

2024-11-29 16:25 UTC, mohitchaurasia91 commented
> Please add a section/comment on verifying the change- is there a way to see how many GPUs nvidia-smi has requested for e.g.?

Updated PR description with logs from test jobs running on develop and feature branch.

2024-12-03 13:05 UTC, annuay-google approved these changes
LGTM

2024-12-03 13:07 UTC, merged